apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: pdf-ingestion
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
  clusterIP: None

